In [40]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error
import matplotlib.pyplot as plt
import seaborn as sns

In [41]:
dataset=pd.read_csv("teacher_profile_scores_12_months.csv")
X=dataset.iloc[:,2:-1].values
y=dataset.iloc[:,-1].values
print(X)
print(y)

[[ 91.    4.9  99.  ...   3.9   4.    3.5]
 [ 95.    4.3 123.  ...   3.8   1.    3.5]
 [ 96.    3.8 107.  ...   3.7   1.    4.7]
 ...
 [ 85.    3.7  91.  ...   4.4   1.    4. ]
 [ 97.    4.2 118.  ...   5.    4.    4.3]
 [ 98.    3.8 119.  ...   4.1   4.    4.3]]
[52.03055556 51.075      50.175      ... 51.22559703 55.47861573
 51.63209757]


In [42]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2, random_state=0)
print(X_train)
print(X_test)
print(y_train)
print(y_test)

[[ 99.    4.  136.  ...   4.7   4.    3.5]
 [ 99.    4.   97.  ...   3.8   1.    4.4]
 [ 91.    3.7  94.  ...   3.7   1.    4.9]
 ...
 [ 93.    3.6 136.  ...   4.4   1.    3.8]
 [ 96.    4.3 145.  ...   4.5   2.    4.9]
 [ 98.    4.8 121.  ...   4.3   4.    3.6]]
[[ 95.    4.8 105.  ...   5.    1.    4. ]
 [ 85.    4.2 118.  ...   4.4   2.    5. ]
 [ 86.    4.2 113.  ...   4.6   4.    3.8]
 ...
 [ 85.    4.7 129.  ...   4.4   4.    4.4]
 [ 97.    3.9 128.  ...   3.8   4.    3.7]
 [ 98.    4.6 136.  ...   3.8   2.    3.9]]
[52.6831825  51.36976043 50.64558    ... 50.90436111 55.17887583
 53.58030056]
[56.19930389 54.28636167 52.77872683 ... 54.73527222 50.4964524
 51.60941667]


In [43]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train[:,3:]=sc.fit_transform(X_train[:,3:])
X_test[:,3:]=sc.fit_transform(X_test[:,3:])
print(X_train)

[[ 9.90000000e+01  4.00000000e+00  1.36000000e+02 ...  9.96038160e-01
   1.33765011e+00 -1.76645365e+00]
 [ 9.90000000e+01  4.00000000e+00  9.70000000e+01 ... -1.06300472e+00
  -1.31645414e+00  2.92522341e-01]
 [ 9.10000000e+01  3.70000000e+00  9.40000000e+01 ... -1.29178726e+00
  -1.31645414e+00  1.43639789e+00]
 ...
 [ 9.30000000e+01  3.60000000e+00  1.36000000e+02 ...  3.09690535e-01
  -1.31645414e+00 -1.08012832e+00]
 [ 9.60000000e+01  4.30000000e+00  1.45000000e+02 ...  5.38473076e-01
  -4.31752722e-01  1.43639789e+00]
 [ 9.80000000e+01  4.80000000e+00  1.21000000e+02 ...  8.09079927e-02
   1.33765011e+00 -1.53767854e+00]]


In [44]:

rf_model = RandomForestRegressor(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)



RandomForestRegressor(random_state=42)

In [46]:
y_pred=rf_model.predict(X_test)
print(y_pred)

[56.09983295 54.40765962 52.85889242 ... 54.52083616 50.15829463
 51.80561103]


In [47]:
print(np.concatenate((y_test.reshape(len(y_test),1),y_pred.reshape(len(y_pred),1)),1))

[[56.19930389 56.09983295]
 [54.28636167 54.40765962]
 [52.77872683 52.85889242]
 ...
 [54.73527222 54.52083616]
 [50.4964524  50.15829463]
 [51.60941667 51.80561103]]


In [57]:

rmse = mean_squared_error(y_test, y_pred, squared=False)
mae = mean_absolute_error(y_test, y_pred)

print(f"Root Mean Squared Error (RMSE): {rmse}")
print(f"Mean Absolute Error (MAE): {mae}")

# print accuracy
accuracy = rf_model.score(X_test, y_test)
print(accuracy)

Root Mean Squared Error (RMSE): 0.3504987427009683
Mean Absolute Error (MAE): 0.26152661459645804
0.9664380507681221


C:\Users\madha\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(


In [61]:
# predict on random data
import numpy as np

random_data = np.array([[
    95,  # Feature 2
    4,  # Feature 3
    147,  # Feature 4
    4,  # Feature 5
    57,  # Feature 6
    77,  # Feature 7
    4.1,  # Feature 8
    3,  # Feature 9
    4.3,  # Feature 10
]])

prediction = rf_model.predict(random_data)
print(prediction)

[55.62018631]
